version: '3.9'
services:
  readme.user.mongo:
    image: mongo:4.2
    restart: always
    container_name: readme.user.mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_MONGO_NAME}
    ports:
      - ${DB_MONGO_PORT}:27017

    volumes:
      - readme.mongo.user:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/${DB_MONGO_NAME} --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  readme.user.mongo.ui:
    image: mongo-express:1.0.2-20
    restart: always
    container_name: readme.user.mongo.ui
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${DB_MONGO_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DB_MONGO_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_MONGO_USER}:${DB_MONGO_PASSWORD}@readme.user.mongo:27017/
volumes:
  readme.mongo.user:
