version: '3.9'
services:
  readme.blog.postgres:
    image: postgres:14-alpine
    restart: always
    container_name: readme.blog.postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - readme.postgres.blog:/var/lib/postgresql/data

    networks:
      - readme.blog

  readme.blog.pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: readme.blog.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - 8082:80
    depends_on:
      - readme.blog.postgres
    networks:
      - readme.blog
volumes:
  readme.postgres.blog:
networks:
  readme.blog:
    driver: bridge
